### PR TITLE
Fix bun test payload echo failure

### LINKED ISSUE #463: `bun test` fails
I would like `bun test` to be passing again :(

### PR DESCRIPTION
**Pull request by alceops**
Fixes #463

## Summary
- Keeps the service payload echo behavior aligned with the server contract: JSON POST bodies still receive the internal `session_id` before invoking service handlers.
- Tightens the echo regression so it explicitly expects the session id instead of stripping it out.
- Preserves empty-body safety with `ctx.body ?? {}`.

## Verification
- `bun test --timeout 20000 platform/test/server.test.ts -t 'echoes back an object with a session id'` → pass
- `bun test --timeout 20000 platform/test/server.test.ts` → 7 passed
- `git diff --check`

Notes on local setup: this runner used Bun plus a local Poetry/Python shim with the minimal dependencies needed by the existing tests. No secrets, service API keys, deploys, account/payment setup, or production data were used.

### CODE REVIEW

File: platform/src/middleware/services.ts [hunk 1]
```diff
@@ -34,8 +34,7 @@ export default async (app: Elysia, port: number) => {
       // simple post
       app.post(name, async (ctx) => {
         console.log(`POST /services/${name}: ${ctx.uuid}`);
-        const payload = ctx.body;
-        payload.session_id = ctx.uuid;
```
Comment (josephjclark) [inline platform/src/middleware/services.ts:38]: We need this session id! Or at least we will soon.

Please update the test to expect it, rather than stripping it out.

Thank you!

**Review by josephjclark — CHANGES_REQUESTED** [review]

**Comment by alceops** [comment]
Thanks — updated to keep `session_id` in the service payload and changed the echo regression to expect it instead of stripping it.

Verification (local shim: Bun + minimal Poetry/Python deps):
- `bun test --timeout 20000 platform/test/server.test.ts -t 'echoes back an object with a session id'` ✅
- `bun test --timeout 20000 platform/test/server.test.ts` ✅ 7 passed
- `git diff --check` ✅

**Review by josephjclark — APPROVED** [review]
Thank you @alceops !!
